# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

require 'google/protobuf/duration_pb'
require 'lint_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("server.proto", :syntax => :proto3) do
    add_message "gitaly.ServerInfoRequest" do
    end
    add_message "gitaly.ServerInfoResponse" do
      optional :server_version, :string, 1
      optional :git_version, :string, 2
      repeated :storage_statuses, :message, 3, "gitaly.ServerInfoResponse.StorageStatus"
    end
    add_message "gitaly.ServerInfoResponse.StorageStatus" do
      optional :storage_name, :string, 1
      optional :readable, :bool, 2
      optional :writeable, :bool, 3
      optional :fs_type, :string, 4
      optional :filesystem_id, :string, 5
      optional :replication_factor, :uint32, 6
    end
    add_message "gitaly.DiskStatisticsRequest" do
    end
    add_message "gitaly.DiskStatisticsResponse" do
      repeated :storage_statuses, :message, 1, "gitaly.DiskStatisticsResponse.StorageStatus"
    end
    add_message "gitaly.DiskStatisticsResponse.StorageStatus" do
      optional :storage_name, :string, 1
      optional :available, :int64, 2
      optional :used, :int64, 3
    end
    add_message "gitaly.ClockSyncedRequest" do
      optional :ntp_host, :string, 1
      optional :drift_threshold_millis, :int64, 2
      optional :drift_threshold, :message, 3, "google.protobuf.Duration"
    end
    add_message "gitaly.ClockSyncedResponse" do
      optional :synced, :bool, 1
    end
    add_message "gitaly.ReadinessCheckRequest" do
      optional :timeout, :message, 1, "google.protobuf.Duration"
    end
    add_message "gitaly.ReadinessCheckResponse" do
      oneof :Result do
        optional :ok_response, :message, 1, "gitaly.ReadinessCheckResponse.Ok"
        optional :failure_response, :message, 2, "gitaly.ReadinessCheckResponse.Failure"
      end
    end
    add_message "gitaly.ReadinessCheckResponse.Ok" do
    end
    add_message "gitaly.ReadinessCheckResponse.Failure" do
      repeated :failed_checks, :message, 1, "gitaly.ReadinessCheckResponse.Failure.Response"
    end
    add_message "gitaly.ReadinessCheckResponse.Failure.Response" do
      optional :name, :string, 1
      optional :error_message, :string, 2
    end
  end
end

module Gitaly
  ServerInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ServerInfoRequest").msgclass
  ServerInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ServerInfoResponse").msgclass
  ServerInfoResponse::StorageStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ServerInfoResponse.StorageStatus").msgclass
  DiskStatisticsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.DiskStatisticsRequest").msgclass
  DiskStatisticsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.DiskStatisticsResponse").msgclass
  DiskStatisticsResponse::StorageStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.DiskStatisticsResponse.StorageStatus").msgclass
  ClockSyncedRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ClockSyncedRequest").msgclass
  ClockSyncedResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ClockSyncedResponse").msgclass
  ReadinessCheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ReadinessCheckRequest").msgclass
  ReadinessCheckResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ReadinessCheckResponse").msgclass
  ReadinessCheckResponse::Ok = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ReadinessCheckResponse.Ok").msgclass
  ReadinessCheckResponse::Failure = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ReadinessCheckResponse.Failure").msgclass
  ReadinessCheckResponse::Failure::Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ReadinessCheckResponse.Failure.Response").msgclass
end
